# Generated by Django 6.0.7 on 2026-07-24 17:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
