# Generated by Django 6.0.7 on 2026-07-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpiece',
            name='newsletter_sent',
            field=models.BooleanField(default=False),
        ),
    ]
